# Generated by Django 2.2.8 on 2019-12-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_board_main', '0002_auto_20191203_0844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
    ]
